server:
  port: 8181
spring:
  sql:
    init:
      platform: postgres
#      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springdb
    username: spring
    password: springpass
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default:
          schema: demo
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    root: WARN
    '[com.example.exibition]': DEBUG
springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /api-ui-html
    operations-sorter: method
    
  
