server:
  port: 8181
spring:
  sql:
    init:
      platform: postgres
#      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db01
    username: igdc
    password: 123.abc
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: WARN
    '[com.example.exibition.controller]': DEBUG
springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /api-ui-html
    operations-sorter: method 
    
jwt:
  secret: password
  